version: '3.6'

services:

    web:
        build:
            context: ./conf/nginx
        restart: always
        env_file: .env
        depends_on:
            - php7xdebug
            - mysql
            - redis
            - mailcatcher
        volumes:
            - ./conf/nginx/conf:/etc/nginx
            - ./workspace:/data
        links:
            - php7xdebug:fpm7
            - mailcatcher
        ports:
            - 80:80
            - 443:443
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 1m


    mysql:
        image: mariadb:latest
        env_file: .env
        ports:
            - 3307:3306
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-proot"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 1m
        volumes:
            - ./conf/mysql/conf:/etc/mysql/conf.d
            - ./data/mysql:/var/lib/mysql
        restart: always


    redis:
        image: redis:latest
        restart: always
        volumes:
            - ./data/redis:/data
        ports:
            - 6379:6379
        healthcheck:
            test: ["CMD", "redis-cli","ping"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 1m


    mailcatcher:
        image: schickling/mailcatcher
        restart: always


    php7console:
        env_file: .env
        build:
            args:
                - TZ=${TZ}
            context: ./conf/php7console
        container_name: php7console
        restart: always
        volumes:
            - ./workspace:/data
        tty: true
        healthcheck:
            test: ["CMD", "pidof","php-fpm"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 1m


    php7xdebug:
        env_file: .env
        build:
            context: ./conf/php7xdebug
        restart: always
        volumes:
            - ./workspace:/data
        links:
            - mysql
            - mailcatcher
            - redis
        healthcheck:
            test: ["CMD", "pidof","php-fpm"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 1m


    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        volumes:
            - /sessions
        depends_on:
            - mysql
        env_file: .env
        ports:
            - 8081:80
